# Goal: Build the image for DevBoard frontend and push it to DockerHub whenever a change is made to the code in the main branch.
name: CI

on:
  push:
    branches: [main] #when a change is made to the main branch, trigger the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Use the latest version of Ubuntu as the runner environment
    steps:
      - name: Checkout code # Checkout the repository code
        uses: actions/checkout@v7 # Checkout the repository code

      - name: Docker Login # Log in to DockerHub
        uses: docker/login-action@v4 # Log in to DockerHub using the provided username and password
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }} # Use the DockerHub username stored in GitHub variables for authentication
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Use the DockerHub token stored in GitHub secrets for authentication
          
      - name: Build and Push Docker Image # Build and push the Docker image to DockerHub
        uses: docker/build-push-action@v7 # Use the Docker Build and Push Action
        with:
          context: ./frontend           # Build context should be the frontend directory
          file: ./Dockerfile            # Dockerfile path relative to the build context
          push: true # Push the built image to the registry
          tags: ${{ vars.DOCKERHUB_USERNAME }}/devboard-fe-main:latest # Use the DockerHub username and image name for the tag
          