# 1. Goal -I have to do SAST for Code

name: Code Quality

on:
  workflow_call: # you can call this workflow from another workflow

jobs:
    sast:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v7
            - name: Set up Node.js
              uses: actions/setup-node@v6 # Set up Node.js environment
              with:
                node-version: '20' # Specify the Node.js version to use
                cache: npm
                cache-dependency-path: frontend/package-lock.json
            - name: Install dependencies
              run: npm ci --legacy-peer-deps # Install project dependencies using npm ci with legacy peer dependencies

            - name: Run ESLint Tests # Run ESLint to check for code style issues
              run: npm run lint # Run the frontend lint script

            - name: Run Tests # Run frontend tests
              run: npm run test # Execute the frontend test script
              working-directory: frontend
            

            - name: Set up Go # Set up Go environment
              uses: actions/setup-go@v6 # Use the Go setup action
              with:
                go-version: '1.23' # Specify the Go version to use
                go-version-file: backend/go.mod # Specify the path to the go.mod file for version management
                cache-dependency-path: backend/go.sum # Specify the path to the go.sum file for caching dependencies

            - name: Run GO Format # Run gofmt to check for code formatting issues
              run: go fmt ./... # Format all Go files

            - name: Run GO Vet # Run go vet to check for code issues
              run: go vet ./... # Vet all Go files

            - name: Run GO Test # Run Go tests
              run: go test ./... # Execute all Go tests
              working-directory: backend
