# 2. To Run End to End DevSecOps CI Pipeline
name: DevSecOps

on: 
  push:
    branches: [feat/matrix-docker-build] # Trigger the workflow on changes to the advanced branch
jobs:
    # Use the code-quality workflow defined in the .github/workflows/code-quality.yml file
    code-quality:
        uses: ./.github/workflows/code-quality.yml 
